import "../styles/globals.css";
import "../styles/theme.scss";
import Head from "next/head";
import Style from "../styles/globalStyle";
import General from "../contexts/General";
import Theme from "../contexts/Theme";
import Layout from "../components/Layout";
import { ParallaxProvider } from "react-scroll-parallax";
import React from "react";

function MyApp({ Component, pageProps }) {
  return (
    <ParallaxProvider>
      <General>
        <Head>
          <title>OrdNServe</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Theme>
          {(theme) => (
            <>
              <Style theme={theme} />
              <Layout>
                <Component {...pageProps} />
              </Layout>
            </>
          )}
        </Theme>
      </General>
    </ParallaxProvider>
  );
}

export default MyApp;
